### ISSUE TITLE
Addition of 2D nesting datasets (irregular C&P)

### ISSUE THREAD

**Issue by JeroenGar** [Oscar-Oliveira/OR-Datasets#1]
Hello,

I previously worked on rectangular 2D C&P algorithms and found your repository extremely handy when benchmarking on the existing data sets from the academic literature.

Right now, I have moved on to 2D nesting problems (irregular shapes instead of rectangles) and would like to contribute to this repository by converting several datasets in a common format.
I propose a similar format to the existing JSON format but with references to separate DXF files which describe the shapes of the polygons.

Would you be open to this idea?

**Comment by Oscar-Oliveira** [comment]
Hi, I am glad to know that the repo was helpful. Sorry for the delay in responding, but I am finishing some works. 
If you agree, I would make you a collaborator of this repo, and you would create a maintain folders for the problems that you are currently working. I really think that would be a great new resource for the repo and for the community.

If you want to communicate more effectively my email is oscar.m.oliveira@gmail.com.

Best regards, 
Óscar
